#!/bin/bash
# Vercel Build Script
# Switches Prisma to PostgreSQL schema for production, then builds

set -e

echo "🔧 Switching Prisma to PostgreSQL schema for production build..."

# Step 1: Copy production schema (PostgreSQL) over the default schema
cp prisma/schema.prod.prisma prisma/schema.prisma

echo "✅ Schema switched to PostgreSQL"

echo "📋 Verifying schema datasource..."
grep 'provider' prisma/schema.prisma | head -1

# Step 2: Generate Prisma client with PostgreSQL provider
# This overwrites any client generated by postinstall (which uses SQLite)
echo "🔧 Generating Prisma client for PostgreSQL..."
npx prisma generate

echo "✅ Prisma client generated for PostgreSQL"

# Step 2b: Push schema changes to the production database
echo "🔧 Pushing schema changes to production database..."
npx prisma db push --accept-data-loss || echo "⚠️ prisma db push failed (may be non-fatal if schema is already up to date)"
echo "✅ Database schema synced"

# Step 3: Verify DATABASE_URL is set
if [ -z "$DATABASE_URL" ]; then
  echo "⚠️  WARNING: DATABASE_URL is not set! The app will fail to connect to Supabase."
  echo "   Set these environment variables in Vercel:"
  echo "   - DATABASE_URL (pooler connection with ?pgbouncer=true)"
  echo "   - DIRECT_URL (direct connection)"
  echo "   - JWT_SECRET (production secret)"
else
  echo "✅ DATABASE_URL is set"
  # Check if pgbouncer parameter is included
  if echo "$DATABASE_URL" | grep -q "pgbouncer"; then
    echo "✅ pgbouncer parameter detected in DATABASE_URL"
  else
    echo "⚠️  WARNING: DATABASE_URL does not include ?pgbouncer=true"
    echo "   This may cause issues with Supabase connection pooling."
  fi
fi

if [ -z "$DIRECT_URL" ]; then
  echo "⚠️  WARNING: DIRECT_URL is not set!"
else
  echo "✅ DIRECT_URL is set"
fi

if [ -z "$JWT_SECRET" ]; then
  echo "⚠️  WARNING: JWT_SECRET is not set!"
else
  echo "✅ JWT_SECRET is set"
fi

# Step 4: Build Next.js with increased memory
echo "📦 Building Next.js..."
NODE_OPTIONS="--max-old-space-size=3072" npx next build

echo "✅ Build complete!"
